-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.carrinho
(
    id serial NOT NULL,
    idcliente integer,
    data date,
    CONSTRAINT carrinho_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.carrinho_itens
(
    idcarrinho integer,
    idproduto integer
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    id serial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT categorias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id serial NOT NULL,
    nome character varying(150) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    celular character varying(14) COLLATE pg_catalog."default",
    senha character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.produtos
(
    id serial NOT NULL,
    idcategoria integer,
    nome character varying(250) COLLATE pg_catalog."default",
    preco double precision,
    foto character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT produtos_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.carrinho
    ADD CONSTRAINT carrinho_idcliente_fkey FOREIGN KEY (idcliente)
    REFERENCES public.cliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.carrinho_itens
    ADD CONSTRAINT carrinho_itens_idcarrinho_fkey FOREIGN KEY (idcarrinho)
    REFERENCES public.carrinho (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.carrinho_itens
    ADD CONSTRAINT carrinho_itens_idproduto_fkey FOREIGN KEY (idproduto)
    REFERENCES public.produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT produtos_idcategoria_fkey FOREIGN KEY (idcategoria)
    REFERENCES public.categorias (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;